name: razer_chroma_rest_server
description: A Razer Chroma SDK REST API server implementation.
version: 0.1.0
homepage: https://github.com/Razer-Chroma-Dart/razer_chroma.dart/tree/master/razer_chroma_rest_server

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.8.0

  ## Razer Chroma
  razer_chroma:
    path: ../razer_chroma
  razer_chroma_rest_core:
    path: ../razer_chroma_rest_core

  ## Server
  shelf: ^1.3.1
  shelf_plus: ^1.4.0

  ## Data
  json_annotation: ^4.6.0
  uuid: ^3.0.6

dev_dependencies:
  ## Language
  lint: ^1.8.2
