name: razer_chroma_rest_core
description: Core components used by the Razer Chroma REST API client and server implementations.
version: 0.1.0
homepage: https://github.com/Razer-Chroma-Dart/razer_chroma.dart/tree/master/razer_chroma_rest_core

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.8.0
  collection: ^1.16.0

  # Razer Chroma
  razer_chroma:
    path: ../razer_chroma

  ## Code generation
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  ## Language
  lint: ^1.8.2

  ## Code generation
  build_runner: ^2.2.0
  freezed: ^2.0.5
  json_serializable: ^6.3.1
