name: razer_chroma_rest_server_macos
description: A razer_chroma_rest_server backend for macOS.
version: 0.1.0
homepage: https://github.com/Razer-Chroma-Dart/razer_chroma.dart/tree/master/razer_chroma_rest_server_macos

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ## Razer Chroma
  razer_chroma_rest_server:
    path: ../razer_chroma_rest_server
  razer_chroma_macos:
    path: ../razer_chroma_macos

dev_dependencies:
  ## Language
  lint: ^1.8.2

  ## Example
  path: ^1.8.2
