name: razer_chroma_macos
description: Bindings to the Razer Chroma macOS library (librazermacos), with a Dart-friendly wrapper.
version: 0.1.0
homepage: https://github.com/Razer-Chroma-Dart/razer_chroma_macos

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ## Language
  meta: ^1.8.0
  collection: ^1.16.0
  ffi: ^2.0.1

  ## Razer Chroma
  razer_chroma:
    path: '../razer_chroma'

dev_dependencies:
  ## Linting
  lint: ^1.8.2

  ## Code generation
  ffigen: ^6.0.1

  ## Example
  path: ^1.8.2

ffigen:
  name: RazerMacOSDriver
  description: Bindings to the Razer Chroma macOS library (librazermacos).
  output: lib/src/driver.dart
  headers:
    entry-points:
      - 'driver/src/include/razeraccessory_driver.h'
      - 'driver/src/include/razerchromacommon.h'
      - 'driver/src/include/razercommon.h'
      - 'driver/src/include/razerdevice.h'
      - 'driver/src/include/razeregpu_driver.h'
      - 'driver/src/include/razerheadphone_driver.h'
      - 'driver/src/include/razerkbd_driver.h'
      - 'driver/src/include/razerkraken_driver.h'
      - 'driver/src/include/razermouse_driver.h'
      - 'driver/src/include/razermousedock_driver.h'
      - 'driver/src/include/razermousemat_driver.h'
    include-directives:
      - 'driver/src/include/**.h'
